# pancharts —geo 地理坐标可视化

基于pyecharts的可视化工具，配置语法与原生的echarts保持一致，完全兼容pandas的数据结构

老师自己开发！

https://github.com/wisherg/pancharts

https://echarts.apache.org/zh/api.html#echarts

### 安装

pip install pancharts -i https://mirrors.aliyun.com/pypi/simple/

### 更新

* 更新前请先保存你的配置文件！

pip install --upgrade pancharts -i https://mirrors.aliyun.com/pypi/simple/

In [1]:
import numpy as np
import pandas as pd
from pancharts import echat,pchat,k2_nv,k2_nv,k_v,km_nv,Pancharts,create_visual_map,gk_vm
import pancharts as pc

In [2]:
pc.__version__

'0.1.4.1'

## 内置agent的使用与全局配置

In [3]:
from pancharts.utils import get_config_file_path

config_path = get_config_file_path()
print(config_path)

d:\soft\anaconda\Lib\site-packages\pancharts\chart_config.py

## k_v的地理可视化

In [3]:
province_list = ["湖南省","浙江省","安徽省","福建省","江西省","山东省"]
provice_data = pd.Series(np.random.randint(0, 100, size=len(province_list)), index=province_list)
print(provice_data)

湖南省    73
浙江省    30
安徽省    85
福建省    60
江西省    83
山东省    22
dtype: int32

In [4]:
province_plot=pc.k_v(provice_data)
province_plot.map("china",{"series":[{"label":False}]}).render_notebook()

## k_vm的geo地理坐标可视化

In [5]:
print(gk_vm.__doc__)

用于可视化pandas中的表示地理数据的单列索引、多列数值型数据的DataFrame,单列索引为地理位置名称，多列默认前两列为经纬度。

In [6]:
#把下面这个数据转化为数据框，name为索引,后面value分为四列，分别为经度、纬度、人口、收入
z=[
        {"name": "北京", "value": [116.46, 39.92, 800,90,"市"]},
        {"name": "上海", "value": [121.48, 31.22, 900,70,"市"]},
        {"name": "广州", "value": [113.23, 23.16, 700,50,"省"]},
        {"name": "深圳", "value": [114.07, 22.62, 600,40,"省"]},
        {"name": "成都", "value": [104.06, 30.67, 500,20,"省"]}
      ]
    
z1={'经度':[],'纬度':[],'人口':[],'收入':[],'类型':[]}
z1_index=[]
for i in z:
  z1['经度'].append(i['value'][0])
  z1['纬度'].append(i['value'][1])
  z1['人口'].append(i['value'][2])
  z1['收入'].append(i['value'][3])
  z1['类型'].append(i['value'][4])
  z1_index.append(i['name'])

geo_df=pd.DataFrame(z1,index=z1_index)
geo_df

        经度     纬度   人口  收入 类型
北京  116.46  39.92  800  90  市
上海  121.48  31.22  900  70  市
广州  113.23  23.16  700  50  省
深圳  114.07  22.62  600  40  省
成都  104.06  30.67  500  20  省

In [9]:
chinamap=gk_vm(geo_df,"china")
p1=chinamap.scatter()
p1.render_notebook()

In [10]:
p1=chinamap.escatter()
p1.render_notebook()

In [11]:
p1=chinamap.heatmap()
p1.render_notebook()

In [12]:
p1=chinamap.bar3d()
p1.render_notebook()

In [13]:
p1=chinamap.scatter(3,"symbolSize")
p1.render_notebook()

In [14]:
p1=chinamap.scatter([2,3],["color","symbolSize"])
p1.render_notebook()

## 高德地图api的注册与使用（国内地址）

https://lbs.amap.com/

单月15000次请求

* 国外开源地图api的，国内外地址皆可搜，就是慢一点

https://opencagedata.com/

 2,500 API requests/day

In [15]:
from pancharts.utils import geocode_amap,geocode_opencage

In [38]:
geocode_amap("九江")

(115.95356, 29.66116)

In [17]:
geocode_opencage("俄罗斯")

(97.7453061, 64.6863136)

In [19]:
a=pd.read_csv(r"e:\shoes.csv")
a["sales"]=a.sales.str.replace("人付款","").astype(int)
a["gmv"]=a.sales*a.price

In [20]:
city=a.location.str.split(" ",expand=True)[1]

In [22]:
city_size=a.groupby(city).size()

In [27]:
pd.DataFrame([{"a":"123","b":"456"}])

     a    b
0  123  456

In [36]:
import time

In [39]:
city_list=[]
lng_list=[]
lat_list=[]
for i in city_size.index:
    city_list.append(i)
    z=geocode_amap(i)
    time.sleep(0.3)
    print(z)
    lng_list.append(z[0])
    lat_list.append(z[1])

(117.943064, 28.45513)
(113.751884, 23.021016)
(113.392517, 22.517024)
(118.356464, 35.103771)
(119.923249, 28.467694)
(115.95356, 29.66116)
(115.464523, 38.874476)
(118.796624, 32.059344)
(118.081325, 27.382829)
(115.857972, 28.682976)
(118.08891, 24.479627)
(121.42079, 28.655716)
(117.227267, 31.820567)
(120.755623, 30.746814)
(112.549656, 37.870451)
(119.547729, 26.666222)
(121.62454, 29.860258)
(117.115349, 30.531828)
(114.416826, 27.816245)
(118.275228, 33.963186)
(119.974092, 31.811313)
(105.844004, 32.435774)
(113.264499, 23.130061)
(117.283752, 34.204224)
(109.488076, 30.272104)
(104.066301, 30.572961)
(119.412834, 32.394404)
(120.209903, 30.246566)
(124.825321, 45.14191)
(114.304569, 30.593354)
(116.681956, 23.354152)
(123.464675, 41.677576)
(118.675724, 24.874452)
(117.120128, 36.652069)
(114.057939, 22.543527)
(121.385435, 28.372805)
(120.699279, 27.993849)
(120.086881, 30.894178)
(119.161721, 36.707668)
(113.576892, 22.271644)
(114.514976, 38.042007)
(120.582886, 30.051549)
(120.585294, 31.299758)
(117.675828, 36.214895)
(118.859307, 28.970229)
(112.121743, 32.010161)
(106.628201, 26.646694)
(119.221487, 34.596639)
(114.49742, 37.060227)
(113.625351, 34.746303)
(119.647265, 29.079195)
(119.424441, 32.188141)
(120.382665, 36.066938)
(115.038999, 30.201082)

In [46]:
city_shoes=pd.DataFrame({'city':city_list,'lng':lng_list,'lat':lat_list,'size':city_size.values})
city_shoes.set_index('city',inplace=True)
city_shoes.head()

             lng        lat  size
city
上饶    117.943064  28.455130     1
东莞    113.751884  23.021016     8
中山    113.392517  22.517024     1
临沂    118.356464  35.103771    15
丽水    119.923249  28.467694   938

In [52]:
city_s_p=gk_vm(city_shoes,"china")
city_s_p_s=city_s_p.scatter()
city_s_p_s.render_notebook()

In [53]:
city_s_p_s=city_s_p.bar3d()
city_s_p_s.render_notebook()

## 地图上的网络

In [55]:
egdes=[["温州","上饶"],["温州","汕头"]]
city_s_p.graph(egdes).render_notebook()

In [57]:
egdes=[["温州","上饶"],["温州","汕头"]]
z1=city_s_p.line3d(egdes)
z1.render_notebook()

In [ ]:
z1.patch_option("让边变粗一些")
z1.render_notebook()

In [61]:
z1.option

{'init': {'echarts_source': 'local',
  'width': '60%',
  'height': '400px',
  'renderer': 'canvas',
  'theme': ''},
 'color': ['#d87c7c',
  '#919e8b',
  '#d7ab82',
  '#6e7074',
  '#61a0a8',
  '#efa18d',
  '#787464',
  '#cc7e63',
  '#724e58',
  '#4b565b'],
 'backgroundColor': '#081027',
 'textStyle': {},
 'title': {'textStyle': {'color': '#333'},
  'subtextStyle': {'color': '#aaa'},
  'left': 'center'},
 'tooltip': {'trigger': 'item',
  'formatter': "JsCode:function(params) { return params.name + '<br/>values:' + params.value; }"},
 'geo3D': {'shading': 'lambert',
  'boxHeight': 8,
  'itemStyle': {'color': '#152949',
   'borderColor': '#2f5597',
   'borderWidth': 1},
  'map': 'china'},
 'series': [{'type': 'lines3D',
   'coordinateSystem': 'geo3D',
   'effect': {'show': True,
    'trailWidth': 1.5,
    'trailOpacity': 0.5,
    'trailLength': 0.2,
    'constantSpeed': 5},
   'blendMode': 'lighter',
   'lineStyle': {'width': 3, 'opacity': 0.25},
   'data': [{'coords': [[120.699279, 27.993849], [117.943064, 28.45513]]},
    {'coords': [[120.699279, 27.993849], [116.681956, 23.354152]]}]}]}