# pancharts 基础作图方法

基于pyecharts的可视化工具，配置语法与原生的echarts保持一致，完全兼容pandas的数据结构

老师自己开发！

https://github.com/wisherg/pancharts

https://echarts.apache.org/zh/api.html#echarts

### 安装

pip install pancharts -i https://mirrors.aliyun.com/pypi/simple/

### 更新

pip install --upgrade pancharts -i https://mirrors.aliyun.com/pypi/simple/

In [1]:
import numpy as np
import pandas as pd
import pancharts as pc

In [29]:
pc.__version__

'0.1.3'

In [1]:
import sys

# 当前Python解释器完整路径
python_exe_path = sys.executable
print(python_exe_path)

d:\soft\anaconda\python.exe

## 大模型配置

https://platform.deepseek.com/

其他模型也支持

In [2]:
from pancharts.utils import get_config_file_path

config_path = get_config_file_path()
print(config_path)

d:\soft\anaconda\Lib\site-packages\pancharts\chart_config.py

In [2]:
# 需要在上面的配置文件中设置大模型的API密钥、接口地址和模型名称
DEFAULT_AI_API_KEY = ""              # 你的大模型 API 密钥
DEFAULT_AI_BASE_URL = ""             # 大模型接口地址，如 https://api.openai.com/v1
DEFAULT_AI_MODEL_NAME = ""           # 所用大模型名称，如 gpt-4o、deepseek-chat 等

## 基于大模型的可视化配置

* 全局配置项的使用

In [3]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
pc_s=pc.k_v(s)#初始化k_v对象
pc_bar=pc_s.bar({"init":{"theme":"dark"}})#绘制柱状图,其中的额外配置可以为空
pc_bar.render_notebook()#在notebook中显示图表

In [25]:
s.index.dtype

In [27]:
pd.api.types.is_string_dtype(s.index.dtype)

True

In [24]:
pd.api.types.is_categorical_dtype(s.index.dtype)

C:\Users\wangp\AppData\Local\Temp\ipykernel_31652\2634323543.py:1: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  pd.api.types.is_categorical_dtype(s.index.dtype)

False

In [22]:
s

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [18]:
pc_bar.option

{'init': {'echarts_source': 'online',
  'width': '60%',
  'height': '400px',
  'renderer': 'canvas',
  'theme': 'dark'},
 'color': ['#d87c7c',
  '#919e8b',
  '#d7ab82',
  '#6e7074',
  '#61a0a8',
  '#efa18d',
  '#787464',
  '#cc7e63',
  '#724e58',
  '#4b565b'],
 'backgroundColor': 'rgba(254,248,239,1)',
 'textStyle': {},
 'title': {'textStyle': {'color': '#333333'},
  'subtextStyle': {'color': '#aaa'}},
 'legend': {'bottom': 0, 'left': 'center'},
 'grid': {'show': True},
 'series': [{'type': 'bar',
   'data': [('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6)],
   'name': None}],
 'xAxis': {'type': 'value'},
 'yAxis': {'type': 'value'}}

In [17]:
s.dtype

dtype('int64')

In [16]:
pd.api.types.is_object_dtype(s)

False

In [9]:
pc_bar.render()

'index.html'

In [6]:
pc_bar.option

{'init': {'echarts_source': 'online',
  'width': '60%',
  'height': '400px',
  'renderer': 'canvas',
  'theme': 'vintage'},
 'legend': {'bottom': 0, 'left': 'center'},
 'grid': {'show': True},
 'series': [{'type': 'bar',
   'data': [('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6)],
   'name': None}],
 'xAxis': {'type': 'category'},
 'yAxis': {'type': 'value'}}

In [3]:
#pc_bar.dmerge({"init":{"width":"100%"}})
#pc_bar.patch_option("增加工具箱，提供图表导出、刷新、数据视图等功能",verbose=True)
#pc_bar.patch_option("增加垂直的线",verbose=True)
#pc_bar.patch_option("请让不同的柱子有不同的颜色",verbose=True)
#pc_bar.patch_option("增加一个最大值的markpoint",verbose=True)
#pc_bar.patch_option("增加一个中位数的markline",verbose=True)
#pc_bar.patch_option("增加一个x轴的datazoom",verbose=True)
pc_bar.patch_option("把柱子变成红色",verbose=True)
pc_bar.render_notebook()

AI Model Response:
{
    "series": [{
        "itemStyle": {
            "color": "red"
        }
    }]
}

## classwork 1

* 请获得大模型的API密钥、接口地址和模型名称，并将其配置在上面的配置文件中，然后通过一个例子完成一个图形的配置变更

* 更改GLOBAL_DEFAULT_CONFIG参数，使图表的宽度和高度更符合你的需求.

## series序列的可视化 k_v

In [4]:
print(pc.k_v.__doc__)

用于可视化pandas中的单列索引序列数据（Series）。

主要功能：
    - 自动将pandas Series转换为ECharts可接受的数据格式
    - 自动判断索引类型（category或value）与数值类型（category或value）
    - 支持通过config参数传入额外的图表配置，与默认配置合并
    - 提供多种常用图表类型的可视化方法

支持的图表类型：
    - bar: 柱状图
    - line: 折线图
    - scatter: 散点图
    - escatter: 增强散点图
    - pie: 饼图
    - funnel: 漏斗图
    - wordcloud: 词云图
    - calendar: 日历热图
    - map: 地图可视化

参数：
    data: pandas Series - 要可视化的数据

用法示例：
    from pancharts import k_v
    import pandas as pd

    data = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
    chart = k_v(data).bar()
    chart.render()

In [10]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
s

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [11]:
pc_s=pc.k_v(s)

In [12]:
pc_s.funnel().render_notebook()

In [6]:
pc_s.pie().render_notebook()

## classwork2

groupby与序列可视化

1. shoes数据导入
2. 可视化前10个商品的价格
2. 求不同"info.鞋面内里材质"的数量，并做对应的可视化
3. 求不同"info.鞋面内里材质"的平均价格，并做可视化

In [15]:
a=pd.read_csv(r"e:\shoes.csv")
a["sales"]=a.sales.str.replace("人付款","").astype(int)
a["gmv"]=a.sales*a.price

In [26]:
a.groupby('info.鞋面内里材质').price.mean()

info.鞋面内里材质
PU         278.668000
二层猪皮       225.754068
人造短毛绒      239.516364
人造长毛绒      290.712500
仿毛         151.500000
兔毛         243.500000
头层牛皮       608.821057
头层猪皮       306.791023
布          234.356419
无内里        243.166136
棉          178.202424
涤沦         368.230769
纯羊毛        340.000000
网纱         167.610476
羊毛羊绒混纺     206.200000
羊皮        1358.714286
超纤         230.354167
Name: price, dtype: float64

In [27]:
top10=pc.k_v(a.groupby('info.鞋面内里材质').price.mean())

In [29]:
top10.funnel({"title":{"text":"鞋面内里材质分布"}}).render_notebook()

In [24]:
pc.k_v(a.price.head(10)).line().render_notebook()

In [25]:
p1=a.groupby('info.鞋面内里材质').size()
p1_kv=pc.k_v(p1)

In [26]:
p1_kv.line().render_notebook()

In [27]:
p10=a.groupby('info.鞋面内里材质').price.mean()
p10_kv=pc.k_v(p10)
p10_kv.bar().render_notebook()

In [28]:
p1=a.groupby("info.鞋面内里材质").size()

In [29]:
p1.sort_values(inplace=True,ascending=False)

In [30]:
p1_kv=pc.k_v(p1)

In [31]:
p1_kv.bar().render_notebook()

In [32]:
p1_kv.pie().render_notebook()

In [33]:
p2=a.groupby("info.鞋面内里材质").price.mean()

In [34]:
p2_kv=pc.k_v(p2)

In [35]:
p2_kv.scatter().render_notebook()

## 时间序列与简单地图

### 时间序列

* 轴类型的区别 {"xAxis":{"type":"time"}}

In [2]:
# 生成一个包含时间序列索引的序列
time_series = pd.date_range(start='2023-01-01', end='2023-12-31', freq='D')
#值为随机整数
random_data = pd.Series(np.random.randint(0, 100, size=len(time_series)), index=time_series)
print(random_data)

2023-01-01    61
2023-01-02    83
2023-01-03    49
2023-01-04    78
2023-01-05    74
              ..
2023-12-27    21
2023-12-28    68
2023-12-29     0
2023-12-30    94
2023-12-31    63
Freq: D, Length: 365, dtype: int32

In [ ]:
date_plot=pc.k_v(random_data)
date_plot.line({"xAxis":{"type":"time"}}).render_notebook()

:

In [41]:
date_plot.calendar().render_notebook()

### 简单地图

* 名字匹配

In [42]:
#帮我生成一个索引为中国省份的序列，省名称后面要加“省”字，值为随机整数
# 定义中国省份列表
province_list = ["湖南省","浙江省","安徽省","福建省","江西省","山东省"]
provice_data = pd.Series(np.random.randint(0, 100, size=len(province_list)), index=province_list)
print(provice_data)

湖南省     4
浙江省    16
安徽省    27
福建省    88
江西省    12
山东省    79
dtype: int32

In [47]:
province_plot=pc.k_v(provice_data)
province_plot.map("china",{"series":[{"label":False}]}).render_notebook()

In [ ]:
#地图可以自由调取
province_plot.map("浙江",{"series":[{"label":False}]}).render_notebook()

## classwork3

1. 做各个省的销售量地图

2. 导入alibaba数据，做日行为量的时序图

In [54]:
loc0=a.location.str.split(" ",expand=True)[0].apply(get_province_name)

In [55]:
a.groupby(loc0).sales.sum()

0
上海市      117
北京市       16
吉林省        0
四川省       23
安徽省        8
山东省        8
山西省       12
广东省       59
江苏省      366
江西省        1
河北省      196
河南省       44
浙江省    22618
湖北省        3
福建省      270
贵州省        0
辽宁省       10
重庆市        1
Name: sales, dtype: int64

In [57]:
pc.k_v(a.groupby(loc0).sales.sum()).map("china",{"series":[{"label":False}]}).render_notebook()

In [43]:
loc=a.location.str.split(" ",expand=True)

In [52]:
#定义一个函数，输入一个省名，返回省名+“省”字，但是如果是直辖市则加“市”
def get_province_name(province):
    if province in ["北京","上海","重庆","天津"]:
        return province+"市"
    else:
        return province+"省"

In [46]:
loc0=loc[0].apply(get_province_name)

In [55]:
loc_data=a.groupby(loc0).gmv.sum()

In [56]:
pc.k_v(loc_data).map("china",{"series":[{"label":False}]}).render_notebook()

In [6]:
r1=pd.read_csv(r"e:\t_alibaba_data3.txt",names=["user","brand","behavr","date"],sep="\t",dtype={"behavr":int})
r1.date="2012/" + r1.date
r1.head()

       user  brand  behavr        date
0  10944750  13451       0  2012/06/04
1  10944750  13451       2  2012/06/04
2  10944750  13451       2  2012/06/04
3  10944750  13451       0  2012/06/04
4  10944750  13451       0  2012/06/04

In [7]:
date_num=r1.groupby(r1.date).size()

In [8]:
date_num.index

Index(['2012/04/15', '2012/04/16', '2012/04/17', '2012/04/18', '2012/04/19',
       '2012/04/20', '2012/04/21', '2012/04/22', '2012/04/23', '2012/04/24',
       ...
       '2012/08/06', '2012/08/07', '2012/08/08', '2012/08/09', '2012/08/10',
       '2012/08/11', '2012/08/12', '2012/08/13', '2012/08/14', '2012/08/15'],
      dtype='object', name='date', length=123)

In [ ]:
pc.k_v(r1.groupby(r1.date).size()).calendar().render_notebook()

:

## 双层索引数值序列（k2_nv）的可视化

In [29]:
print(pc.k2_nv.__doc__)

用于可视化pandas中的两层索引、单列数值型数据的序列（Series）。

主要功能：
    - 自动将具有双层索引的pandas Series转换为ECharts可接受的数据格式
    - 支持通过config参数传入额外的图表配置，与默认配置合并
    - 提供关系型和三维数据可视化的图表类型
    - 支持为图网络数据指定节点分类

支持的图表类型：
    - bar3d: 3D柱状图
    - graph: 图网络
    - sankey: 桑基图
    - heatmap: 热力图

参数：
    data: pandas Series - 要可视化的数据，需具有双层索引结构
    cate: list, optional - 图网络节点分类，长度为2的列表

用法示例：
    from pancharts import k2_nv
    import pandas as pd

    # 创建具有双层索引的数据（通常由两列groupby产生）
    data = pd.Series(
        [10, 20, 30, 40],
        index=pd.MultiIndex.from_product([['A', 'B'], ['x', 'y']])
    )
    chart = k2_nv(data).heatmap()
    chart.render()

In [ ]:
a1

a  x    1
   y    2
b  x    3
   y    4
c  x    5
   y    6
dtype: int64

In [ ]:
a1=pd.Series([1,2,3,4,5,6],index=pd.MultiIndex.from_tuples([('a','x'),('a','y'),('b','x'),('b','y'),('c','x'),('c','y')]))
k2_nv0=pc.k2_nv(a1)

In [ ]:
k2_nv0.sankey().render_notebook()

In [ ]:
a1

a  x    1
   y    2
b  x    3
   y    4
c  x    5
   y    6
dtype: int64

## classwork2

双层groupby的可视化

1. 不同'info.鞋面材质',"info.风格"的商品数量，然后按照数量倒序
2. 可视化上面结果

In [ ]:
p2=a.groupby(['info.鞋面材质',"info.风格"]).size().sort_values(ascending=False)
p2_k2nv=pc.k2_nv(p2)
p2_k2nv.sankey().render_notebook()

In [ ]:
p2_k2nv.heatmap().render_notebook()

In [ ]:
p2=a.groupby(['info.鞋面材质',"info.风格"]).size().sort_values(ascending=False)
p2

info.鞋面材质   info.风格
头层牛皮（除牛反绒）  商务         1618
            休闲         1170
PU          休闲          395
二层牛皮（除牛反绒）  休闲          271
            商务          221
                       ...
头层猪皮        韩版            1
太空革         商务            1
塑胶          休闲            1
牛仔布         韩版            1
太空革         韩版            1
Length: 75, dtype: int64

In [ ]:
p2_2kvn=pc.k2_nv(p2)
p2_2kvn.heatmap().render_notebook() #jupyter notebook 中显示图表

In [ ]:
p2_2kvn=pc.k2_nv(p2)
p2_2kvn.graph().render_notebook()

## 多层索引数值序列（km_nv）的可视化

In [ ]:
print(pc.km_nv.__doc__)

    支持多列索引和单列数值型数据序列（series）。

    功能：
    1. 转换序列为echarts可接受的格式,见特征sun_tree_data,treemap_data,tree_data。
    2. 提供sunburst,treemap,tree 等方法，
       分别对应不同的可视化图表类型，图形对象与Pyecharts的图像对象是一致的，因此也支持Pyecharts的基础方法。
    3. 作图方法可以传入额外的图表配置，参数类型为字典，语法与echarts的配置语法一致，然后会合并数据配置项与默认配置项完成作图。

    例子：
    #生成一个三层索引的数值序列
    s1=pd.Series([1,2,3,4,5,6],index=pd.MultiIndex.from_tuples([('a','b','c'),('a','b','d'),('a','c','e'),('a','c','f'),('b','d','g'),('b','d','h')]))
    pc_s=km_nv(s1)#初始化km_nv对象

    pc_sunburst=pc_s.sunburst({"title":{"text":"simple sun tree"}})#绘制旭日图,其中的额外配置可以为空
    pc_sunburst.render()#渲染为html文件

    pc_tree=pc_s.tree()#这里会基于最外层索引值个数生成若干颗树，默认选择第0颗
    pc_tree.render_notebook()

In [ ]:
s

a  b  c    1
      d    2
   c  e    3
      f    4
b  d  g    5
      h    6
dtype: int64

In [16]:
s=pd.Series([1,2,3,4,5,6],index=pd.MultiIndex.from_tuples([('a','b','c'),('a','b','d'),('a','c','e'),('a','c','f'),('b','d','g'),('b','d','h')]))
pc_s=pc.km_nv(s)#初始化km_nv对象
pc_tree=pc_s.sunburst()#这里会基于最外层索引值个数生成若干颗树，默认选择第0颗
pc_tree.render_notebook()

In [17]:
pc_tree.patch_option("通过series的levels让三层环的逐个变窄",verbose=True)

AI Model Response:
{
    "series": [{
        "levels": [
            {"r0": "0%", "r": "40%"},
            {"r0": "40%", "r": "70%"},
            {"r0": "70%", "r": "90%"}
        ]
    }]
}

In [18]:
pc_tree.render_notebook()

In [ ]:
pc_tree=pc_s.treemap()#这里会基于最外层索引值个数生成若干颗树，默认选择第0颗
pc_tree.render_notebook()

## classwork3

更多层groupby的可视化

1. 获取商品数前五的店铺
2. 对这些店铺商品记录的"nick",'info.风格','info.款式'进行groupby，得到不同店铺下不同特征的男鞋数量
3. 可视化上面结果

In [ ]:
nicklist=a.groupby("nick").size().sort_values(ascending=False).head().index.tolist()

In [ ]:
p3=a[a.nick.isin(nicklist)].groupby(["nick",'info.风格','info.款式']).size()
p3_kmnv=pc.km_nv(p3)
p3_kmnv.tree().render_notebook()

In [ ]:
p3_kmnv.sunburst().render_notebook()

In [ ]:
p3_kmnv.treemap().render_notebook()

In [ ]:
nick_list=a.groupby("nick").size().sort_values(ascending=False).head(5).index.tolist()
p3=a[a.nick.isin(nick_list)].groupby(["nick",'info.风格','info.款式']).size()

In [ ]:
p3.head()

nick      info.风格  info.款式
意尔康男鞋旗舰店  休闲       休闲皮鞋       28
                   休闲高帮皮鞋      2
                   商务休闲鞋       4
                   懒人鞋         2
                   户外休闲鞋       7
dtype: int64

In [ ]:
p3_kmnv=pc.km_nv(p3)

In [ ]:
p3_kmnv.sunburst().render_notebook()

In [ ]:
p3_kmnv.treemap().render_notebook()

## 多列数值型数据（vm）可视化

In [ ]:
print(pc.vm.__doc__)

    用于可视化pandas中的（索引无要求, 多列数值型数据radar,parallel图可以对象型）序列（series）。

    功能：
    1. 支持序列传入，自动转换序列为echarts可接受的格式：parallel_data,radar_data。
    2. 基于上面数据生成对应的数据配置项：parallel_data_option,radar_data_option。
    3. 提供 parallel、radar 等方法，
       分别对应不同的可视化图表类型，图形对象与Pyecharts的图像对象是一致的，因此也支持Pyecharts的基础方法。

    例子：
    df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['x','y','z'])
    vm0=vm(df)
    vm0.radar().render_notebook()


    df=pd.DataFrame([[1,2,3,'a'],[4,5,6,'b'],[7,8,9,'c']],index=['a','b','c'],columns=['x','y','z','w'])
    vm0=vm(df)
    vm0.parallel().render_notebook()

In [6]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['x','y','z'])
vm0=pc.k_vm(df)
vm0.radar().render_notebook()

In [10]:
vm0.radar().options

{'series': [{'type': 'radar',
   'data': [{'name': 'a', 'value': [1, 2, 3, 'a']},
    {'name': 'b', 'value': [4, 5, 6, 'b']},
    {'name': 'c', 'value': [7, 8, 9, 'c']}]}],
 'legend': {'data': ['a', 'b', 'c']},
 'radar': {'indicator': [{'name': 'x', 'max': 7, 'min': 1},
   {'name': 'y', 'max': 8, 'min': 2},
   {'name': 'z', 'max': 9, 'min': 3},
   {'name': 'w', 'max': 'c', 'min': 'a'}]}}

In [ ]:
df

   x  y  z
a  4  2  3
b  4  5  6
c  7  8  9

In [9]:
df=pd.DataFrame([[1,2,3,'a'],[4,5,6,'b'],[7,8,9,'c']],index=['a','b','c'],columns=['x','y','z','w'])
vm0=pc.k_vm(df)
vm0.parallel().render_notebook()

In [19]:
p2=vm0.parallel()

In [40]:
# 线的颜色改为不同颜色
p2.options["series"][0]["data"]=[{'name': 'a', 'value': [1, 2, 3, 'a'],"lineStyle":{"color":"red"}},
    {'name': 'b', 'value': [4, 5, 6, 'b'],"lineStyle": { "color": 'blue' }},
    {'name': 'c', 'value': [7, 8, 9, 'c'],"lineStyle": { "color": 'green' }}]

In [38]:
p2.options

{'series': [{'type': 'parallel',
   'lineStyle': {'width': 4},
   'data': [{'name': 'a',
     'value': [1, 2, 3, 'a'],
     'itemStyle': {'color': 'red'}},
    {'name': 'b', 'value': [4, 5, 6, 'b'], 'itemStyle': {'color': 'blue'}},
    {'name': 'c', 'value': [7, 8, 9, 'c'], 'itemStyle': {'color': 'green'}}]}],
 'parallelAxis': [{'dim': 0, 'name': 'x', 'type': 'value'},
  {'dim': 1, 'name': 'y', 'type': 'value'},
  {'dim': 2, 'name': 'z', 'type': 'value'},
  {'dim': 3, 'name': 'w', 'type': 'category', 'data': ['a', 'b', 'c']}]}

In [41]:
p2.render_notebook()

## classwork4

多列数据框的可视化

1. 求不同店铺的统计指标（price_mean, gmv_sum, gmv_mean, sales_mean, sales_sum, size）
2. 可视化不同店铺的统计指标

In [ ]:
nick_tz=a.groupby("nick").agg(price_mean=("price", "mean"), 
                      gmv_sum=("gmv", "sum"),
                      gmv_mean=("gmv", "mean"),
                      sales_mean=("sales", "mean"),
                      sales_sum=("sales", "sum"),
                      size=("nick", "size"),
                      ).sort_values(by="gmv_sum", ascending=False)
nick_tz

           price_mean    gmv_sum      gmv_mean  sales_mean  sales_sum  size
nick
意尔康皮鞋旗舰店   485.712803  3558446.0  12312.961938   47.833910      13824   289
意尔康男鞋旗舰店   680.812081   792685.0   5320.033557   17.953020       2675   149
意尔康品牌店     271.461538   114452.0   1760.800000    7.661538        498    65
乙方乙方88888  164.666667    88144.0   9793.777778   60.333333        543     9
吸引力xl      152.000000    43870.0   8774.000000   59.000000        295     5
...               ...        ...           ...         ...        ...   ...
yek108     398.666667        0.0      0.000000    0.000000          0     3
热血无极限      148.885000        0.0      0.000000    0.000000          0     2
燕轩品牌店      178.000000        0.0      0.000000    0.000000          0     1
爱鞋坊2012    379.333333        0.0      0.000000    0.000000          0     3
龙凤吉祥4249   158.666667        0.0      0.000000    0.000000          0     3

[482 rows x 6 columns]

In [ ]:
p4=nick_tz.head(5)
p4_vm=pc.vm(p4)

In [ ]:
p4_vm.radar().render_notebook()

In [ ]:
p4_vm.parallel().render_notebook()